# Generated by Django 5.0 on 2023-12-12 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_project_project_id_alter_timesheet_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_id',
            field=models.CharField(default='c56165047f97', editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='hours_worked',
            field=models.DurationField(),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='week_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
